### PR TITLE
WIP: ENH:  Add Xvfb support to Docker image

### PR DESCRIPTION
**Pull request by sjh26**
Requires: https://github.com/Slicer/DashboardScripts/pull/37

Add Xvfb support to allow graphics based tests to run through the Docker image

- [x] Test cleaned up version
- [x] Refactor to move the env variables out of the dashboard script to the docker image
- [ ] After merge: build and push image

### CODE REVIEW

**Comment by sjh26** [comment]
Still requires a bit more testing to make sure all of the added packages are actually necessary, best places to set environment variables, etc.

**Comment by lassoan** [comment]
This will be great, thanks for working on it!

**Comment by sjh26** [comment]
Build results:

https://slicer.cdash.org/build/2183435

11 failures, none seem to be graphics related.

**Comment by lassoan** [comment]
This is awesome, already very useful.

There are a couple of errors due to too wide module widget:

>Line 194 qSlicerModelsModule widget has a minimum size hint width of 502px. It is wider than the maximum allowed width of 500px. (maximum allowed width computed as: 500px or 30% of screen width of 800px)

Could we make the screen size wider to make it more representative of current screen resolutions (for example, 1920x1080) or change screen scaling?
If that is not possible or we think that the widgets are actually too wide then that's fine, too, then we need to fix the module widgets to make them narrower.

**Comment by sjh26** [comment]
Sure, I can fiddle around with the screen size when launching xvfb.

Current settings:

````
Xvfb :99 -screen 0 1024x768x24 +extension GLX +render -noreset &
````

**Comment by sjh26** [comment]
I think the 800px may be coming from the "offscreen" plugin rather than the xvfb, have put that on the list.  I am going to transfer the list to an issue, since I want to merge this today to get most of the test working for tomorrow.

**Comment by sjh26** [comment]
Merged, along with changes to dashboard scripts.  We should be good to go for the next nightly

**Comment by jcfr** [comment]
:partying_face:

**Pull request merged**
