### PR TITLE
qt5-centos7: Update from 5.12.8 to 5.15.0

### PR DESCRIPTION
**Pull request by jamesobutler**
This updates qt5-centos7 to use Qt 5.15.0

From ToDo list in:
https://discourse.slicer.org/t/build-failure-windows/7322/37

### CODE REVIEW

**Comment by jamesobutler** [comment]
Note: I actually haven't tried this updated build environment yet, and there is likely still some issues especially now that Qt download tool requires a Qt account to download.

**Comment by sjh26** [comment]
Yeah, I am working on a solution for providing the account info.  Once I get that merged we'll merge this.

**Comment by sjh26** [comment]
PR for account details (WIP) https://github.com/Slicer/SlicerBuildEnvironment/pull/14

**Comment by sjh26** [comment]
@jamesobutler, could you rebase this?

**Comment by sjh26** [comment]
@jcfr, once this is merged, I pull push the updated image

**Comment by jamesobutler** [comment]
I've rebased now

**Comment by jcfr** [comment]
> once this is merged, I pull push the updated image

I suggest we tag the current image with `slicer-4.11-2020.05.27` and update the README, and use this image for SlicerSALT. See https://github.com/Slicer/DashboardScripts/blob/87a8a09f108759dc142f36c62f660bb0013bef34/metroplex.sh#L69-L76

See https://github.com/Slicer/SlicerBuildEnvironment#tagging-a-build-environment-image

**Comment by sjh26** [comment]
By current do you mean the 5.15.8 we just merged?  The 5.11.2 won't build anymore.

**Comment by jamesobutler** [comment]
I also just realized that it was updated to 5.12.8 in the other PR.  I've removed the remaining white space changes that were left in my original commit to update to 5.12.8 and have now just left the commit to update further to 5.15.0.

**Comment by jamesobutler** [comment]
Slicer salt should still be able to build with Qt 5.12.8 without any real issue. Maybe only with SSL incompatibilities, but it should still be able to build without having to update Slicer salt to an updated slicer version.

**Comment by sjh26** [comment]
Current image has been pushed.  I will update the SALT dashboard scripts.

**Comment by jcfr** [comment]
Sounds good. And we will fix SlicerSALT if needed.

**Comment by sjh26** [comment]
Yeah, I have a backlog of "broken SALT things"  from this factory update push 😺

**Comment by sjh26** [comment]
New image with Qt 5.15 has been pushed as latest

**Pull request merged**
