### PR TITLE
ENH: Update qt5-centos7 build env to Qt 5.11.0

### PR DESCRIPTION
**Pull request by sjh26**
Test build in in progress

### CODE REVIEW

**Comment by sjh26** [comment]
Build is good and the extension manager doesn't crash!

**Comment by jcfr** [comment]
Great. What is your dockerhub username ? I will grant you access to the slicer organization on dockerhub so that you can publish the updated image

**Comment by sjh26** [comment]
dockerhub user is samhorvath

https://hub.docker.com/u/samhorvath/

**Comment by jcfr** [comment]
Great. After login using:

```
docker login -u samhorvath
```

You should be able to publish using:

```
cd Docker
make qt5-centos7.push
```

**Comment by sjh26** [comment]
done

**Comment by jcfr** [comment]
Humm ... the compressed image is 1.5GB, I wonder if anything changed

**Comment by sjh26** [comment]
yeah, I was wondering about that too.

**Comment by jcfr** [comment]
Look like the image now include `*.debug` libraries, after confirming I will publish an update

**Comment by sjh26** [comment]
not sure how that happened...

**Comment by jcfr** [comment]
```
$ cd /opt/qt/5.11.0/gcc_64
$ du -h | grep -E "\./\w+$"
3.3M	./mkspecs
540M	./plugins
404M	./bin
2.5G	./lib
162M	./qml
320K	./phrasebooks
47M	./include
564K	./doc
20M	./resources
27M	./translations
264K	./libexec
```

```
$ cd /opt/qt/5.10.1/gcc_64
$ du -h | grep -E "\./\w+$"
3.2M	./mkspecs
22M	./plugins
42M	./bin
209M	./lib
22M	./qml
320K	./phrasebooks
45M	./include
564K	./doc
21M	./resources
28M	./translations
16K	./libexec
```

**Pull request merged**
